# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import   QFileDialog,QSlider
from viewer import ImageViewer
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2000, 1200)
        # self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView = ImageViewer()
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1600, 1200))
        self.graphicsView.setParent(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1600, 0, 400, 1200))
        self.widget.setObjectName("widget")
        self.enable_mask_btn = QtWidgets.QPushButton(self.widget)
        self.enable_mask_btn.setGeometry(QtCore.QRect(100, 600, 200, 40))
        self.enable_mask_btn.setAutoDefault(False)
        self.enable_mask_btn.setDefault(False)
        self.enable_mask_btn.setObjectName("enable_mask_btn")

        self.load_img_btn = QtWidgets.QPushButton(self.widget)
        self.load_img_btn.setGeometry(QtCore.QRect(100, 500, 200, 40))
        self.load_img_btn.setObjectName("load_img_btn")
        self.save_mask_btn = QtWidgets.QPushButton(self.widget)
        self.save_mask_btn.setGeometry(QtCore.QRect(100, 700, 200, 40))
        self.save_mask_btn.setObjectName("save_mask_btn")

        self.next_btn = QtWidgets.QPushButton(self.widget)
        self.next_btn.setGeometry(QtCore.QRect(100, 800, 200, 40))
        self.next_btn.setObjectName("next_btn")

        self.prev_btn = QtWidgets.QPushButton(self.widget)
        self.prev_btn.setGeometry(QtCore.QRect(100, 900, 200, 40))
        self.prev_btn.setObjectName("prev_btn")

        self.recover_btn = QtWidgets.QPushButton(self.widget)
        self.recover_btn.setGeometry(QtCore.QRect(100, 400, 200, 40))
        self.recover_btn.setObjectName("recover_btn")

        self.slider = QSlider(self.widget)
        self.slider.setGeometry(QtCore.QRect(100, 1000, 200, 40))
        self.slider.setObjectName("slider")
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setMinimum(0)
        self.slider.setMaximum(50)
        self.slider.setValue(10)

        self.slider_label = QtWidgets.QLabel(self.widget)
        self.slider_label.setGeometry(QtCore.QRect(100, 1100, 200, 40))
        self.slider_label.setObjectName("slider_label")
        self.slider_label.setText(f"Slider Value: {self.slider.value()}")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.load_img_btn.clicked.connect(self.load_image)
        self.save_mask_btn.clicked.connect(self.save_mask)
        self.enable_mask_btn.clicked.connect(self.enbale_mask)
        self.next_btn.clicked.connect(self.next_img)
        self.prev_btn.clicked.connect(self.prev_img)
        self.slider.valueChanged.connect(self.handle_slider_change)
        self.recover_btn.clicked.connect(self.recover)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enable_mask_btn.setText(_translate("Form", "Enable Mask"))
        self.load_img_btn.setText(_translate("Form", "Load Image"))
        self.save_mask_btn.setText(_translate("Form", "Save Mask"))
        self.next_btn.setText(_translate("Form", "Next Image"))
        self.prev_btn.setText(_translate("Form", "Prev Image"))
        self.recover_btn.setText(_translate("Form", "Recover"))

    def load_image(self):
        self.folder_path = QFileDialog.getExistingDirectory(QtWidgets.QWidget(),
                  "Open folder",
                  "./")  
        if self.folder_path is not None:
            self.graphicsView.loadInitImg(self.folder_path)
    def enbale_mask(self):
        self.graphicsView.enable_mask()
    def next_img(self):
        self.graphicsView.next_img()
    def prev_img(self):
        self.graphicsView.prev_img()
    def handle_slider_change(self):
        self.graphicsView.change_eraser(self.slider.value())
        self.slider_label.setText(f"Slider Value: {self.slider.value()}")
    def save_mask(self):
        self.graphicsView.save_mask()
    def recover(self):
        self.graphicsView.recover()
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())